### ISSUE TITLE
Прапор замість "нейтрального" значка

### ISSUE THREAD

**Issue by ryzhmann** [denysdovhan/ukrainian-typographic-keyboard#10]
Чи можна все ж таки додати український прапор? Можливо можна це якось винести в налаштування?

**Comment by denysdovhan** [comment]
Привіт! На жаль, з коробки такої опції немає.

Прапорці це кльово, але я відмовився від них на користь уніфікації. Скажімо, який має бути прапорець для англійської розкладки: британський чи американський (чи може канадський, австралійський, тощо)? Замість цього я зробив звичайні крапочки: сіра - латиниця наближена до американської розкладки, рожева - українська кирилиця.

Якщо ви бажаєте замінити на прапорці, ви можете це зробити. Встановіть програму Ukulele (https://software.sil.org/ukelele/), відкрийте у ній бандл та замініть значки на ті, які вам до вподоби.
