### ISSUE TITLE
Уніфікувати позиції символів для обох розкладок

### ISSUE THREAD

**Issue by ww7** [denysdovhan/ukrainian-typographic-keyboard#11]
Дякую, що стрілочки ↑↓←→ на українській ідуть через шифт, це прямо не баг, а фіча.

**Comment by denysdovhan** [comment]
Привіт! До версії 2.0 так і було. Ви можете спробувати встановити її.

Починаючи з 2.0 я зрозумів, що на українській розкладці значно корисніше мати доступ до деяких символів, що йдуть у англійській розкладці. Скажімо, я частіше захочу з української розкладки ввести $ не переключаючись на англійську. Так само з іншими символами. В більшості випадків, додаткові символи можна ввести з допомогою Shift+Option.
