### ISSUE TITLE
Russian-as-primary Ukrainian typographic layout

### ISSUE THREAD

**Issue by denysdovhan** [denysdovhan/ukrainian-typographic-keyboard#2]
Do we need that?

**Comment by ipasikun** [comment]
Russian-as-primary 👍

**Comment by samplenull** [comment]
Is it possible to make Russian layout with Ukrainian symbols available with modifier keys? I don't think everybody needs this, but it can be very convenient to use 2 layouts instead of 3.
Maybe my question should be moved to separate issue for voting?

**Comment by denysdovhan** [comment]
@samplenull I meant exactly what you've said. This issues propose to create an layout with Russian-specific characters available as default and Ukrainian-specific characters available with modifier keys. So if you primary language is Russian, you can choose this layout instead of Ukrainian-based one.

**Comment by samplenull** [comment]
@denysdovhan Thank you

**Comment by denysdovhan** [comment]
@samplenull you're welcome :)

**Comment by ipasikun** [comment]
When will this day come?)

**Comment by nik-holo** [comment]
@ipasikun ipasikun  

You can use this one: https://github.com/golodenko/typography-layout-ua

**Comment by denysdovhan** [comment]
In a view of recent events. I don't think this will ever happen. I don't see any reason to invest in a Russian primary key layout. If anyone wants to type Russian letter, you can do that by using Option key.

This key layout will remain Ukrainian-English only.
