### ISSUE TITLE
Знак ударения вместо одиночной кавычки

### ISSUE THREAD

**Issue by ctrlok** [denysdovhan/ukrainian-typographic-keyboard#3]
Предлагаю в украинской раскладке сделать знак ударения (`) вместо апострофа('). 
Должно получится просто и аналогично английской раскладке.

**Comment by denysdovhan** [comment]
@ctrlok а де тобі має бути апостроф на українській розкладці?

**Comment by SmartFinn** [comment]
@denysdovhan в Ubuntu в раскладке Russian (with Ukrainian-Belorussian layout) ударение ставится по модификатор Level 3 (Right Alt в моем случае) + апостроф:

![screenshot from 2016-12-29 18-37-38](https://cloud.githubusercontent.com/assets/819186/21548678/71235316-cdf6-11e6-873c-849fab426a95.png)

Думаю не сложно такое повторить для вашей раскладки.

**Comment by SmartFinn** [comment]
@denysdovhan вижу у вас на этом месте `ё`, но его можно перенести на `е`, я например привык.

**Comment by denysdovhan** [comment]
@SmartFinn в принципі, можна зробити так, мабуть таке розміщення більш оптимальне. Можете зробити PR?

**Comment by SmartFinn** [comment]
@denysdovhan нет, сорри, уверен что не осилю все нюансы, еще `™` нужно переносить на `⌥` + `т`.

**Comment by denysdovhan** [comment]
@SmartFinn окей, я подивлюсь, коли матиму час. Треба придумати, що робити з цим робити.
