### ISSUE TITLE
Provide install via brew cask

### ISSUE THREAD

**Issue by ihorzenich** [denysdovhan/ukrainian-typographic-keyboard#4]
Please, create brew cask to provide install by `brew cask install ukrainian-typographic-keyboard`.
Thanks!

**Comment by denysdovhan** [comment]
@ihorzenich could you suggest how can I do it?

**Comment by ihorzenich** [comment]
@denysdovhan There is manual: https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#adding-a-cask or you can just ask for creation in Issues: https://github.com/caskroom/homebrew-cask/issues/new?title=Cask%20request%3A%20%5Bapp%20name%20here%5D&body=%23%23%23%20Cask%20details%0A%0A%28Please%20fill%20out%20as%20much%20as%20possible%29%0A%0A%2A%2AName%2A%2A%3A%0A%0A%2A%2AHomepage%2A%2A%3A%0A%0A%2A%2ADownload%20URL%2A%2A%3A%0A%0A%2A%2ADescription%2A%2A%3A%0A

**Comment by denysdovhan** [comment]
@ihorzenich I've opened an issue: https://github.com/caskroom/homebrew-cask/issues/29109

**Comment by denysdovhan** [comment]
@ihorzenich done.
