### ISSUE TITLE
Use the Caps Lock key to switch to and from English

### ISSUE THREAD

**Issue by vasylnahuliak** [denysdovhan/ukrainian-typographic-keyboard#6]
Добавити можливість перемикання за допомогою клавіші **Caps Lock** 
![cap-lock-keyboard-swap](https://user-images.githubusercontent.com/40458927/71008608-8fcceb00-20f1-11ea-8720-82b077e1fa05.png)

**Comment by denysdovhan** [comment]
Should work with v2.0.0
