### ISSUE TITLE
Не працює пермикання мови

### ISSUE THREAD

**Issue by mpodaniev** [denysdovhan/ukrainian-typographic-keyboard#7]
Версія системи 12.4
MacBook Air (M1, 2020)

Перемикання на цю клавіатуру працює тільки в Хромі, та ще в деяких стороннійх програмах. 
Не перемикається в Нотатках, Телеграмі, Слак, Сафарі (це те що протестував).

**Comment by denysdovhan** [comment]
Привіт! Дякую за встановлення!
Це навряд чи повʼязано з самим пакетом, адже він ніяк не впливає на сам механізм перемикання мови, а лише додає розкладку. Переконайтесь, що ви додали обидві розкладки (англійську та українську). Спробуйте перезавантажити ваш мак.

**Comment by mpodaniev** [comment]
Перезаватажував не працювало.
Не зрозумів що значить встановити Англійську, якщо вона в мене і так встановлена. 
Через деякий час зрозумів, не дуже ясно це з опису. Встановив, і з танцями з бубном ледве видалив стандартну англійську.

1. Дуже не помітно яка мова обрана. Сіра і помаранчова точка це дуже не зручно і доводиться вдивлятись щоб зрозуміти що за мова зараз.
2. Там де не працювало почало працювати, але відображається англійська. 
3. І також в цих програмах літери "і" та "и" змінюються місцями.

Тобто заходжу в Телеграмм або Слак мова відображається англійська, хоча коли набираєшь текст то українська. І принаймні дві літери знаходяться не на своїх місцях.

Поки що не можливо цим користуватись

**Comment by mpodaniev** [comment]
Це жесть вирішив перезавантажити мак і виявилось що я не можу ввессти пароль так як не можу змінити мову.
Вибрана англійська але схоже що не англійська так як в мене дуже простий пароль з 4 символами які ідуть підряд.
Досить довго не міг зайти, видаляв мови вводу але українську не можливо видалити вона сіра.
Закінчились спроби входу, перезавантажив ще раз, потім знову закінчились, знову перезавантажив. Не помогало, все одно не ті символи хоча відображається ABC.
Я вже на паніці, потрібно працювати а я комп залочив, це просто жесть.

**Comment by denysdovhan** [comment]
На жаль, я не можу вам допомогти. З вашого опису все це виглядає як збіг користувацьких помилок. З вашого опису мені важко відтворити послідовність подій, яка призвела до поточного стану речей.
