### ISSUE TITLE
[Brew] Cask 'ukrainian-typographic-keyboard' is unavailable: No Cask with this name exists.

### ISSUE THREAD

**Issue by skifgold** [denysdovhan/ukrainian-typographic-keyboard#8]
Інсталяція з допомогою `brew`, не працює 

Команда `brew install --cask ukrainian-typographic-keyboard`  
повертає
Error: Cask 'ukrainian-typographic-keyboard' is unavailable: No Cask with this name exists

<img width="793" alt="Screenshot 2022-07-13 at 22 44 49" src="https://user-images.githubusercontent.com/12040934/178818476-34c72548-75a6-438b-a9ef-4c92b3441949.png">

**Comment by denysdovhan** [comment]
Привіт! Раніше можна було встановити з homebrew, але цей cask видалили. Я подав запит, щоб повернути назад в реєстр cask. Слідкувати за перебігом можна тут: https://github.com/Homebrew/homebrew-cask/pull/127727

**Comment by skifgold** [comment]
Дякую вам пане!
Ваш вклад в український opensource не оцінений

**Comment by denysdovhan** [comment]
Дякую!
До речі, команда `brew install --cask ukrainian-typographic-keyboard` вже повинна працювати.
