### ISSUE TITLE
 Bundle чомусь не працює на MBP M1

### ISSUE THREAD

**Issue by shytikov** [denysdovhan/ukrainian-typographic-keyboard#9]
Привіт! Дякую за апдейт!

Але чомусь не можу встановити його на свому MBP M1. Використовую brew, bundle file знаходиться в `~/Library/Keyboard Layouts`, але чомусь нічого не зʼявляється в Input Sources...

Те саме з англійською...

Вже перевантажувався, не підхоплює... Може є якісь поради?

**Comment by denysdovhan** [comment]
Дуже дивно, у мене М1 Max і все працює чудово.

Можливо ви пропустили маленький + на сторінці Input Sources, який дозволяє додати нові розкладки?

**Comment by ZuBB** [comment]
таки не працює. m1pro

**Comment by ihorvorotnov** [comment]
Схоже таки є проблемка на М1 Pro

![CleanShot 2022-07-15 at 00 13 15@2x](https://user-images.githubusercontent.com/1066083/179087129-b2bd1b65-aa77-42d0-881e-11e4b6b0cc20.jpg)

**Comment by ichcc** [comment]
Наприклад, спроба одредагувати в Ukelele на M1Pro
<img width="372" alt="image" src="https://user-images.githubusercontent.com/8458030/179168599-06244da2-9582-45eb-9011-e7221be4094f.png">

**Comment by vladforfutdinov** [comment]
Якщо покласти в рутовий ```/Library/Keyboard Layouts``` - побачить. Але це якесь не те. З розкладкою Бірмана такої проблеми нема - вона працює з ```~/Library/Keyboard Layouts```.
MacBook Pro (13-inch, M1, 2020)

**Comment by ZuBB** [comment]
> Якщо покласти в рутовий `/Library/Keyboard Layouts` - побачить

ну це вже щось. для старту можна й так. далі побачимо

----

@denysdovhan є ідеї в чому ваш сетап відрізняється від нашого?

**Comment by ZuBB** [comment]
діло не в руті. `brew install` створює якусь дику directory structure. якщо внутрішній "bundle" поставити замість верхнього то воно худо-бідно працює

прапорець не вдалося перемогти. тільки сірий квадрат замість нього.

@denysdovhan можете поправити формулу для brew?

<img width="1058" alt="Screenshot 2022-07-16 at 17 57 45" src="https://user-images.githubusercontent.com/597016/179365529-608d0396-4598-4323-a34f-7b4eec3e4c80.png">

**Comment by ZuBB** [comment]
Короче самарі такий
* в брю качається архів релізу звідси, а в ньому трохи не то (див комент ⬆️ )
* _dmg_ в загальному ок, але в ньому "іконки-точки" 😕.
* іконки можна захачити, якщо просто підмінити файл (але лишити те саме ім'я файлу)
* якщо іконка не відобрається - скоріш за все вона у вас "крива"

Пара прохань до @denysdovhan 
* поправити формулу, бо вона краща за dmg тим що її можна автоапдейтити
* перейменувати розкладку з "Ukrainian" на "Ukrainian - Typographic". так більше зрозуміло про що вона в тому діалогу
* добавити прапорець. бачу 2 причини на то
  * то що епл випилили прапорці є лажою зрозуміло по кількості виття в інеті.
  * те що в нас відбувається сприяє тому що ми хочемо мати ще один спосіб для самоіндентифікації

Пара корисних ссилок 
* https://apple.stackexchange.com/questions/441267/how-do-i-get-back-the-input-source-flags-on-my-menu-bar
* https://discussions.apple.com/docs/DOC-250005181
* https://discussions.apple.com/docs/DOC-250004892

PS: є ще баг що добавляється розкладка "ukrainian - legacy" в список використовуваних. чи це мій локальний баг чи ні незрозуміло. так само не зрозуміло чи це зумовлено цією новою розкладкою (яка має таке саме імя) чи ні. Добре що при переключенні розкладок які бачить система їх все ще 2 🤷🏻 

<img width="222" alt="image" src="https://user-images.githubusercontent.com/597016/179395695-7635c61c-21b4-446c-818d-67a9f485666d.png">

**Comment by denysdovhan** [comment]
Оу, з формулою у brew дійсно факап. Загубився в шляхах. Зараз спробую поправити.

**Comment by denysdovhan** [comment]
Проблема має бути вирішена разом з https://github.com/Homebrew/homebrew-cask/pull/128074

**Comment by ZuBB** [comment]
> Проблема має бути вирішена разом з [Homebrew/homebrew-cask#128074](https://github.com/Homebrew/homebrew-cask/pull/128074)

е-е-е.. а хіба так можна? не треба було бампнути версію?

**Comment by ZuBB** [comment]
@denysdovhan якось прокоментуєте ідеї із перейменуванням та прапорцем?

**Comment by denysdovhan** [comment]
@ZuBB можна, версія клавіатури залишається така ж сама. Змінюється формула для cask.

**Comment by denysdovhan** [comment]
@ZuBB тему прапорця прокоментував тут: https://github.com/denysdovhan/ukrainian-typographic-keyboard/issues/10

Перейменування призведе до того, що вікно перемикання клавіатури стане занадто широким. Перейменувати також можна з допомогою Ukulele, як я описав у коментарі.

**Comment by ZuBB** [comment]
> що вікно перемикання клавіатури стане занадто широким

@denysdovhan ви це маєте на увазі https://i.redd.it/q6zrotbwmhb81.png ?

> Перейменувати також можна з допомогою Ukulele, як я описав у коментарі.

тут би посилання на той коментар не зашкодило

раз про прапорець нічого не відписали, я так розумію ви тоже не в захваті від цієї ідеї?

**Comment by denysdovhan** [comment]
Я ж залишив посилання на #10. Там описав як перейменувати клавіатура та як змінити значок на прапорець.

**Comment by ZuBB** [comment]
> Я ж залишив посилання на #10. Там описав як перейменувати клавіатура та як змінити значок на прапорець.

пробачте, але тільки тепер гітхаб показав мені той комент 🤷🏻

**Comment by ZuBB** [comment]
> PS: є ще баг що добавляється розкладка "ukrainian - legacy" в список використовуваних. чи це мій локальний баг чи ні незрозуміло. так само не зрозуміло чи це зумовлено цією новою розкладкою (яка має таке саме імя) чи ні. Добре що при переключенні розкладок які бачить система їх все ще 2 🤷🏻
> 
> <img alt="image" width="222" src="https://user-images.githubusercontent.com/597016/179395695-7635c61c-21b4-446c-818d-67a9f485666d.png">

і останнє: @denysdovhan а є ідеї чого в мене це стається?

**Comment by denysdovhan** [comment]
Чесно кажучи, уявлення не маю.

**Comment by denysdovhan** [comment]
brew має працювати. ПР прийняли.
